version: "3.8"

services:
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=partiguiden
      - POSTGRES_PASSWORD=secret_pass
      - POSTGRES_DB=partiguiden
    volumes:
      - .tmp/db_dev:/var/lib/postgresql/data