version: "3.8"

services:
  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:6.1
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - .pgadmin:/var/lib/pgadmin
    networks:
      - postgres

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=partiguiden
      - POSTGRES_PASSWORD=secret_pass
      - POSTGRES_DB=partiguiden
    volumes:
      - .tmp/postgresql:/var/lib/postgresql
    networks:
      - postgres

networks:
  postgres:
    driver: bridge